import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Post from "../components/Posts.jsx";
import { useState, useEffect } from "react";
import Menu from "../components/Menu";

export default function Home() {
  let [tweets, set_tweets] = useState(null);

  const Post_Components = [];

  if (tweets) {
    tweets.content.forEach(({ tweet, toxicity }) => {
      Post_Components.push(
        <Post
          user={tweets?.user.name}
          date={""}
          content={tweet.text}
          img_link={""}
          toxicity={toxicity}
        />
      );
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {tweets ? (
        <div>
          <h1>{tweets.user.name}</h1>
          <h2>
            toxicity level {Math.trunc(tweets.average_toxicity * 1000) / 1000}
          </h2>
          {Post_Components}
        </div>
      ) : (
        <Menu set_tweets={set_tweets} />
      )}
    </div>
  );
}
